### ISSUE TITLE
Creating Table if Non-Existent 

### ISSUE THREAD

**Issue by GochoMugo** [angrycoders/jkuatapp-dbapi#1]
I propose a new method, example `$db->CreateTableIfNonExistent`, that allows creating table, if it does **not** exist. Otherwise, it returns without raising any exception (specifically the Exception related to creating an already-existing table).

This is useful while **booting** the application, where we can **not** assume that we are working on a fresh/new machine. Plus it will allows restarting the application without following a different logic path.

**Comment by felix-magani** [comment]
The current `createTable` method does exactly that.,
The naming of the method is what I did wrong.

**Comment by GochoMugo** [comment]
It seems this a **classical** show of the inadequate documentation we are facing.

Since the method already does so, I suggest we keep it named so. However, this logic should be documented.

**Fix:** Document the method so we can close this Issue.
